# Generated by Django 5.2.1 on 2025-05-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderunner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesubmission',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='codesubmission',
            name='output_data',
        ),
        migrations.RemoveField(
            model_name='codesubmission',
            name='result',
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='verdict',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('c', 'C')], max_length=10),
        ),
    ]
