# Generated by Django 5.2.1 on 2025-05-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=20),
        ),
    ]
