# Generated by Django 5.2.1 on 2025-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True),
        ),
    ]
