# Generated by Django 5.2.1 on 2025-05-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_problem_constraints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='constraints',
            new_name='input_prob',
        ),
        migrations.AddField(
            model_name='problem',
            name='output_prob',
            field=models.TextField(blank=True),
        ),
    ]
